### ISSUE TITLE
淘宝客服务商是需要申请还是？

### ISSUE THREAD

**Issue by owen-gxz** [laka-group/tbksdk#1]
我看你实现的接口大部分都是需要用户授权的服务商接口，这个服务商接口需要申请麻？？

**Comment by nagasawaja** [comment]
需要有人跟淘宝小二对接申请，而且比较麻烦

**Comment by owen-gxz** [comment]
恩，我前几天问了下这个还不能申请，只能他联系你们。。你们这个有没有成品阿。。基础api 感觉没什么东西

**Comment by nagasawaja** [comment]
是这么麻烦的，我们这边有专人对接淘宝小二也弄个了2个月左右才能拿回来

**Comment by owen-gxz** [comment]
![image](https://user-images.githubusercontent.com/8510542/68109031-89f5be80-ff24-11e9-8bf1-53ea4ac9294c.png)
你们这样的问题怎么解决的

**Comment by nagasawaja** [comment]
找他们没用，我也找过，所以后来找来运营的人，他们认识内部的小二，需要一些专门的人去弄

**Comment by owen-gxz** [comment]
晕。。还有这要求。。。那就是个人基本搞不了了

**Comment by nekocode** [comment]
@nagasawaja Hi，我们也正在申请淘宝客的接口，目前拿到了他们给的一份申请表格。想问下这里的上下行 appkey 你们是怎么申请的？
![image](https://user-images.githubusercontent.com/4783781/111436652-2fd25380-873d-11eb-8d46-c948e8af5dfb.png)

**Comment by nagasawaja** [comment]
> @nagasawaja Hi，我们也正在申请淘宝客的接口，目前拿到了他们给的一份申请表格。想问下这里的上下行 appkey 你们是怎么申请的？
> ![image](https://user-images.githubusercontent.com/4783781/111436652-2fd25380-873d-11eb-8d46-c948e8af5dfb.png)

新开一个应用，拿一个没用的上下行key去申请就可以。一般有专门的小二对接的

**Comment by nekocode** [comment]
@nagasawaja 可以提供下联系方式么？我们这边想有偿咨询点问题

**Comment by owen-gxz** [comment]
钉钉群：23178116
